# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bradley Golden
tagline:             
url:                 http://bradleygolden.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bradley Golden
  url:               http://bradleygolden.github.io
  email:             golden.bradley@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/bradleygolden/bradleygolden.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
